CREATE TABLE IF NOT EXISTS schema_versions (version INTEGER PRIMARY KEY, applied_at INTEGER NOT NULL, description TEXT);
INSERT OR IGNORE INTO schema_versions (version, applied_at, description) VALUES (1, 0, 'Initial schema');
CREATE TABLE IF NOT EXISTS cost_records (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp INTEGER NOT NULL, provider TEXT NOT NULL, model TEXT NOT NULL, task_type TEXT NOT NULL, input_tokens INTEGER NOT NULL, output_tokens INTEGER NOT NULL, cost_usd REAL NOT NULL);
CREATE TABLE IF NOT EXISTS route_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp INTEGER NOT NULL, task_type TEXT NOT NULL, from_model TEXT NOT NULL, to_model TEXT NOT NULL, to_provider TEXT NOT NULL, latency_ms INTEGER NOT NULL, success INTEGER NOT NULL DEFAULT 1, cost_usd REAL NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS verification_reports (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp INTEGER NOT NULL, files_checked TEXT NOT NULL, diff_result TEXT NOT NULL, hallucinations TEXT NOT NULL, confidence TEXT NOT NULL, test_result TEXT);
CREATE TABLE IF NOT EXISTS model_performance (id INTEGER PRIMARY KEY AUTOINCREMENT, provider TEXT NOT NULL, model TEXT NOT NULL, task_type TEXT NOT NULL, total_requests INTEGER NOT NULL DEFAULT 0, success_count INTEGER NOT NULL DEFAULT 0, avg_latency_ms REAL NOT NULL DEFAULT 0, last_used INTEGER NOT NULL, UNIQUE(provider, model, task_type));
CREATE TABLE IF NOT EXISTS hallucination_rules (id INTEGER PRIMARY KEY AUTOINCREMENT, category TEXT NOT NULL, pattern TEXT NOT NULL, language TEXT NOT NULL DEFAULT 'any', severity TEXT NOT NULL DEFAULT 'medium', message TEXT NOT NULL, suggestion TEXT, enabled INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS trusted_packages (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, language TEXT NOT NULL DEFAULT 'any', source TEXT NOT NULL DEFAULT 'user', created_at INTEGER NOT NULL, UNIQUE(name, language));
CREATE TABLE IF NOT EXISTS graph_nodes (id INTEGER PRIMARY KEY AUTOINCREMENT, file_path TEXT NOT NULL, node_type TEXT NOT NULL, name TEXT NOT NULL, start_line INTEGER NOT NULL, end_line INTEGER NOT NULL, metadata TEXT, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS graph_edges (id INTEGER PRIMARY KEY AUTOINCREMENT, from_id INTEGER NOT NULL REFERENCES graph_nodes(id), to_id INTEGER NOT NULL REFERENCES graph_nodes(id), edge_type TEXT NOT NULL, UNIQUE(from_id, to_id, edge_type));
CREATE INDEX IF NOT EXISTS idx_cost_timestamp ON cost_records(timestamp);
CREATE INDEX IF NOT EXISTS idx_cost_model ON cost_records(model);
CREATE INDEX IF NOT EXISTS idx_cost_task ON cost_records(task_type);
CREATE INDEX IF NOT EXISTS idx_route_timestamp ON route_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_perf_lookup ON model_performance(provider, model, task_type);
CREATE INDEX IF NOT EXISTS idx_rules_category ON hallucination_rules(category);
CREATE INDEX IF NOT EXISTS idx_rules_language ON hallucination_rules(language);
CREATE INDEX IF NOT EXISTS idx_trusted_pkg ON trusted_packages(name);
CREATE INDEX IF NOT EXISTS idx_graph_file ON graph_nodes(file_path);
CREATE INDEX IF NOT EXISTS idx_graph_type ON graph_nodes(node_type);
CREATE INDEX IF NOT EXISTS idx_graph_edge_from ON graph_edges(from_id);
CREATE INDEX IF NOT EXISTS idx_graph_edge_to ON graph_edges(to_id);
CREATE VIRTUAL TABLE IF NOT EXISTS verification_fts USING fts5(id, files_checked, hallucinations, confidence_summary, content='verification_reports', content_rowid='rowid');
